# Generated by Django 4.2.20 on 2025-03-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALERTA_MEDICA', 'Alerta Médica'), ('DIAGNOSTICO_NUEVO', 'Nuevo Diagnóstico'), ('ACTUALIZACION_PACIENTE', 'Actualización de Datos del Paciente'), ('NUEVO_ESTUDIO', 'Nuevo Estudio Médico'), ('INFORME_FINAL', 'Reporte Generado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosticos.diagnostico')),
                ('eeg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.eeg')),
                ('mirna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.mirna')),
                ('mri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.mri')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
