# Generated by Django 3.2.6 on 2025-05-01 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MUESTRA_DE_SANGRE', 'Muestra de sangre'), ('PRESCRIPCION_DE_MEDICAMENTO', 'Prescripcion de medicamento'), ('CONSULTA_MEDICA', 'Consulta medica'), ('EXAMEN_MEDICO', 'Examen medico'), ('CIRUGIA', 'Cirugia'), ('CITA_MEDICA', 'Cita medica')], max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
